version: '3'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  digest:
    build:
      context: .
      dockerfile: Dockerfile.digest
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8003:8003"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - scraper

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - scraper
      - digest
