version: '3'

services:
  digest-app:
    build: .
    volumes:
      - ./data:/app/data  # For persistent storage of articles and digests
      - ./logs:/app/logs  # For log files
      - ./config:/app/config  # For configuration files
      - ./cache:/app/cache  # For cache files
      - ./chromedriver-linux64:/app/chromedriver-linux64
      - /usr/local/bin/chromedriver:/usr/local/bin/chromedriver
    environment:
      - SUPABASE_URL=https://ckywgfnaaiapiyrztgdp.supabase.co
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNreXdnZm5hYWlhcGl5cnp0Z2RwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0Mzk3MDY0NCwiZXhwIjoyMDU5NTQ2NjQ0fQ.kR-jZNfDf8NfddReYx2irUVBh_3AYCLjeBM9UKvjGtw
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNreXdnZm5hYWlhcGl5cnp0Z2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzA2NDQsImV4cCI6MjA1OTU0NjY0NH0.orM89MV8N4Nwdm9JmIWeVhu8-mqZqxdfp7VOZH-zM_s
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNreXdnZm5hYWlhcGl5cnp0Z2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzA2NDQsImV4cCI6MjA1OTU0NjY0NH0.orM89MV8N4Nwdm9JmIWeVhu8-mqZqxdfp7VOZH-zM_s
      - MIXTRAL_API_KEY=OTLFsDf7FEz44mcNREgxun2SDUHvGCVB
      - MIXTRAL_API_ENDPOINT=https://api.mistral.ai/v1/chat/completions
    shm_size: 2gb  # Needed for Chrome in Docker
    restart: unless-stopped  # Add this for auto-restart
    command: python -m wrangler.citydigest.main schedule --run-now  # Change this as needed

  # Add any other environment variables your app needs
