global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "worker"
    static_configs:
      - targets: ["worker:8000"]
    
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]