from .states.arizona.tucson_scraper import TucsonNewsScraper
from .states.california.san_diego_scraper import SanDiegoNewsScraper
from .states.colorado.denver_scraper import DenverNewsScraper
from .states.florida.miami_scraper import MiamiNewsScraper
from .states.illinois.chicago_scraper import ChicagoNewsScraper
from .states.massachusetts.boston_scraper import BostonNewsScraper
from .states.new_mexico.abq_scraper import ABQNewsScraper
from .states.oregon.portland_scraper import PortlandNewsScraper
from .states.texas.austin_scraper import AustinNewsScraper
from .states.texas.dallas_scraper import DallasNewsScraper
from .states.washington.seattle_scraper import SeattleNewsScraper